### PR TITLE
20240313 erc20 wrappers

### LINKED ISSUE #118: erc20 contracts
- [x] create wrapper contracts for ERC20 demurrage and inflation Circles

### PR DESCRIPTION
**Pull request by benjaminbollen**
fixes #118 

⚠️ the base branch for this PR is assuming path transfer #115 has been merged

- [x] starting on ERC20 wrappers, deployment proxy (~~create2~~ do this later)
- [x] reorg demurrage for reuse in ERC1155 and ERC20
- [x] write inflationary first ERC20
- [x] ensure deployments
- [x] mints and burns from Hub
- [x] erc1155-onReceived logic proposal for auto-lift? (probably later)
- [x] ERC20Permit
- [x] fix names in Hub and ERC20

### CODE REVIEW

**Comment by benjaminbollen** [comment]
this has been a big PR. Im going to mark it here for review, and work on the new (required, deterministic) deployment script instead.

Most new functions here are missing the documentation comment, but deliberately leaving them off for now, because I moved around a few things, so I want to come back to review with fresh eyes the code in its current state. With some functions missing the docs it's easier to see where to pay extra attention.

**Comment by benjaminbollen** [comment]
- forgot to implement `name()` for ERC20 to connect it to `NameRegistry` directly
- and the `safeInflationaryTransfer` don't fit in Hub.sol, so I will put them in `erc20Lift.sol` (and come up with a different name for the contract?)

**Comment by benjaminbollen** [comment]
moving this back to review; but there's a bunch of commented out code that moved around for juggling the size reduction. I ll take that out once the deployment script and test deployment is done.

Also I ll need to come back to add the missing docs for the new functions

also the `safeInflationaryTransfer` still needs be put back in a helper contract (no space in Hub.sol)

**Review by jaensen — APPROVED** [review]
FIPF

**Pull request merged**
